apiVersion: v1
kind: MessagePlatformAdapter
metadata:
  name: weworkfinance_media
  label:
    zh_Hans: 企业微信会话存档（媒体增强版）
    en_US: WeWork Finance Archive (Media Enhanced)
spec:
  description:
    zh_Hans: 企业微信会话存档轮询适配器，支持完整下载图片、语音、视频、文件等媒体内容
    en_US: WeWork Finance Archive polling adapter with full support for downloading images, voices, videos, and files
  config_schema:
    type: object
    required:
      - corpid
      - secret
    properties:
      corpid:
        type: string
        description:
          zh_Hans: 企业 ID
          en_US: Corporation ID
      secret:
        type: string
        description:
          zh_Hans: 会话存档的 secret
          en_US: Finance archive secret
      rsa_private_key_path:
        type: string
        description:
          zh_Hans: RSA 私钥文件路径（用于解密消息内容）
          en_US: RSA private key file path (for decrypting messages)
        default: "rsa_private.pem"
      polling_interval:
        type: integer
        description:
          zh_Hans: 轮询间隔（秒）
          en_US: Polling interval (seconds)
        default: 5
        minimum: 1
        maximum: 60
      batch_limit:
        type: integer
        description:
          zh_Hans: 每次拉取的消息数量
          en_US: Number of messages to fetch per request
        default: 100
        minimum: 1
        maximum: 1000
      timeout:
        type: integer
        description:
          zh_Hans: API 超时时间（秒）
          en_US: API timeout (seconds)
        default: 10
        minimum: 5
        maximum: 60
      seq_save_path:
        type: string
        description:
          zh_Hans: seq 游标保存路径
          en_US: Seq cursor save path
        default: "data/wework_finance_seq.txt"
      enable_media_download:
        type: boolean
        description:
          zh_Hans: 是否启用媒体文件下载（图片、语音、视频、文件）
          en_US: Enable media file download (images, voices, videos, files)
        default: true
      media_download_timeout:
        type: integer
        description:
          zh_Hans: 媒体文件下载超时时间（秒）
          en_US: Media file download timeout (seconds)
        default: 30
        minimum: 10
        maximum: 300
      auto_clear_cache_interval:
        type: integer
        description:
          zh_Hans: 自动清空下载缓存间隔（秒），0 表示不自动清空
          en_US: Auto clear download cache interval (seconds), 0 means never
        default: 3600
        minimum: 0
        maximum: 86400
execution:
  python:
    path: pkg/platform/sources/weworkfinance_media.py
    attr: WeWorkFinanceMediaAdapter
