apiVersion: v1
kind: Plugin
metadata:
  author: chenwu
  name: wecom_assistant_plugin
  repository: ''
  version: 0.1.0
  description:
    en_US: 'LangBot plugin for WeCom information collection and reply interception'
    zh_Hans: 'LangBot plugin for WeCom information collection and reply interception'
  label:
    en_US: wecom assistant plugin
    zh_Hans: wecom assistant plugin
  icon: assets/icon.svg  # replace in assets/icon.svg
spec:
  config: []
  components: {}
execution:
  python:
    path: main.py
    attr: wecomassistantplugin