apiVersion: v1
kind: Tool
metadata:
  name: get_user_profile
  label:
    en_US: GetUserProfile
    zh_Hans: GetUserProfile
  description:
    en_US: 'Fetch a WeCom user profile by userid using contacts or app token.'
    zh_Hans: '使用通讯录或应用凭证按userid查询企业微信用户信息。'
spec:
  parameters:
    type: object
    properties:
      user_id:
        type: string
        description: 'WeCom userid to fetch, e.g., zhansan.'
    required:
      - user_id
  llm_prompt: 'Look up WeCom user basic profile data by userid.'
execution:
  python:
    path: get_user_profile.py
    attr: GetUserProfile
