apiVersion: v1
kind: Tool
metadata:
  name: send_wecom_text
  label:
    en_US: SendWecomText
    zh_Hans: SendWecomText
  description:
    en_US: 'Send a text or markdown message through an internal WeCom app.'
    zh_Hans: '通过企业微信自建应用发送文本或Markdown消息。'
spec:
  parameters:
    type: object
    properties:
      user_id:
        type: string
        description: 'Target user IDs separated by |, or @all to broadcast.'
      party_id:
        type: string
        description: 'Target department IDs separated by |.'
      tag_id:
        type: string
        description: 'Target tag IDs separated by |.'
      content:
        type: string
        description: 'Message content; supports WeCom formatting or Markdown if msgtype=markdown.'
      msgtype:
        type: string
        enum: [text, markdown]
        description: 'Use text for plain content or markdown for rich formatting.'
      safe:
        type: boolean
        description: 'Override safe flag for this message; defaults to plugin configuration.'
    required:
      - content
  llm_prompt: 'Send a WeCom message to a user/department/tag using the configured app.'
execution:
  python:
    path: send_wecom_text.py
    attr: SendWecomText
